development:
  auth0_client_id: t31alqzNl7NxbyBQtggNTrr7MdRPm7De #<%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: k8i5HHFJcxEGnJ25zY0VyjCTgStjPVbyxbuMtelM4mT4BjQA0EoUzuB_PY5JAxyv #<%= ENV["AUTH0_CLIENT_SECRET"] %>
  auth0_domain: iadev.auth0.com #<%= ENV["AUTH0_DOMAIN"] %>

test:
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>

production:
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
